### ISSUE TITLE
Hahahaha, is this your freedom of speech? I said the ideas and opinions that are inconsistent with the owner, and then my issue is closed. 

### ISSUE THREAD

**Issue by 0xZhangKe** [caffeine-overload/bandinchina#53] opened 2019-10-11 08:29 UTC
Hahahaha, is this your freedom of speech? I said the ideas and opinions that are inconsistent with the owner, and then my issue is closed.

**Comment by 784033619** [comment] 2019-10-11 08:42
hahaha,just like me,my issue closed too

**Comment by caffeine-overload** [comment] 2019-10-11 09:16
Duplicate of #52

**Closed by caffeine-overload** 2019-10-11 09:16 UTC

**Comment by DropFan** [comment] 2019-10-16 06:44
xswl

**Comment by weathon** [comment] 2019-11-08 03:37
Your freedom is base on others' right, not the govement

**Comment by gusbemacbe** [comment] 2019-11-12 16:11
@0xZhangKe and @784033619 

Know that Android is US-based, as Google as well. Google forbids the Chinese companies of using Android, so you will not be able to develop apps. 

Anyway, you will never control and rule our countries. Your country does not respect our sovereignty. We will not sell our democracy, our freedom, our human rights and our lands to you.
